[package]
name = "hemtt"
version = "0.4.0"
authors = ["Brett <brett@bmandesigns.com>"]
edition = "2018"

[dependencies]
armake2 = "0.3"
colored = "1.7"
docopt = "1"
regex = "*"
reqwest = "0.9"
self_update = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termcolor = "*"
walkdir = "2.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.5"
